### ISSUE TITLE
Automatically reopen primary classes to add mixin.

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-lifeline#1]
Specifically, mix `ember-lifeline/mixins/run` into the following classes:

* `Ember.Component`
* `Ember.Route`
* `Ember.Controller`
* `Ember.Helper`
* `Ember.Service`

And mix `ember-lifeline/mixins/dom` into:

* `Ember.Component`

**Comment by scalvert** [comment]
I don't believe we have plans to do this. Please feel free to reopen if I'm mistaken.
