### ISSUE TITLE
Pass arguments into `runTask`

### ISSUE THREAD

**Issue by offirgolan** [rwjblue/ember-lifeline#15]
I think it should be possible to pass arguments to `runTask`

```js
// this.runTask(callbackOrName, timeout, ...args)
this.runTask('myTask', 500, 'foo', 'bar');
```

**Comment by rwjblue** [comment]
I think the idea here was to keep it simple. If you need this functionality, you can use () => {}...

**Comment by offirgolan** [comment]
Works for me 😄
