### ISSUE TITLE
Add support for Ember.Evented?

### ISSUE THREAD

**Issue by justinaray** [rwjblue/ember-lifeline#16]
# Issue Type
Feature Request/RFC

# Desc
Would it be possible to add a new api or overload `addEventListener` to support subscribing to Ember.Evented?

We utilize some pub/sub services that require similar cleanup, state checking, and testing acrobats that are solved by this library in the jQuery case.

Sorry if this is a silly suggestion or out of scope for this repo.

**Comment by scalvert** [comment]
Great minds think alike! Closing as a dupe of #58.
