### ISSUE TITLE
Enable usage of `Ember.run.schedule`

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-lifeline#2]
This could either be via options passed to `runTask`, or another top level method specifically for this (i.e. `scheduleTask`).

As of https://github.com/emberjs/ember.js/pull/14550 (will be included in 2.8.3, 2.9.1, 2.10.0-beta.3+), it is possible to cancel things scheduled into a specific queue via `Ember.run.schedule`. In a sample application `run.schedule` is one of the primary remaining use cases of `Ember.run` that still requires manual `this.isDestroying` checks.

**Comment by rwjblue** [comment]
@mixonic - Thoughts on the best way to add this?

**Comment by Charizard** [comment]
@rwjblue Also, usage for `Ember.run.next`?

**Comment by rwjblue** [comment]
That is essentially what `this.runTask(() => { /* stuff here */ })` is. It's unlikely that we will provide additional API for run.next other than that.

**Comment by Charizard** [comment]
Without time. Understood 👍

**Comment by offirgolan** [comment]
@rwjblue any progress on this? Haven't `run.schedule` and `run.scheduleOnce` always returned a timer id to be able to cancel them? 

I can take a stab at this if there are no blockers.

**Comment by rwjblue** [comment]
> Haven't run.schedule and run.scheduleOnce always returned a timer id to be able to cancel them?

Actually, no, they have not.  I added support for canceling in 2.8: https://github.com/emberjs/ember.js/pull/14550.

**Comment by rwjblue** [comment]
> I can take a stab at this if there are no blockers.

Sounds good. I think the only real blocker is deciding the API for it...

**Comment by offirgolan** [comment]
@rwjblue Im a fan of splitting the api into `runTask` and `scheduleTask`.

**Comment by offirgolan** [comment]
Also, would this be the only part of the API that would be 2.8+?

**Comment by rwjblue** [comment]
> Also, would this be the only part of the API that would be 2.8+?

I can't recall, but possibly. I think we can mitigate though...

**Comment by mixonic** [comment]
@rwjblue Is there a specific use-case you had in mind for this? Seems ok, just curious under what scenarios this would be useful.

**Comment by scalvert** [comment]
I believe this was implemented in #45
