### ISSUE TITLE
Accept `once` option in addEventListener

### ISSUE THREAD

**Issue by kellyselden** [rwjblue/ember-lifeline#23]
This could clean up uses of `this.$().one` and `this.$().off` in case it hasn't run yet.

It's an official option [here](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) and would join the current supported option https://github.com/rwjblue/ember-lifeline#passive-true

**Comment by rwjblue** [comment]
Yep, seems good to me.  This would add support for the `once` option documented on [MDN for `addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener).

**Comment by scalvert** [comment]
I believe this is addressed in #40, with the conversion to using standard DOM APIs.
