### ISSUE TITLE
Feature Request: drop jQuery dependency

### ISSUE THREAD

**Issue by simonihmig** [rwjblue/ember-lifeline#26]
I think this addon would be another good example where dropping jQuery and using native DOM would make sense!

I wonder if @cibernox might be interested? 😝

**Comment by cibernox** [comment]
I'm fixing ember-exam first, but this is not far in the list.

**Comment by rwjblue** [comment]
FWIW, I wrote a version that didn't use jQuery at one point.  I'll see if I can drum it up to make the job easier for someone...

**Comment by scalvert** [comment]
Fixed in #40.
