### ISSUE TITLE
Expose a `this.cancelTask` method

### ISSUE THREAD

**Issue by mdebbar** [rwjblue/ember-lifeline#30]
Currently, the only way to manually cancel a task is to use `Ember.run.cancel(cancelId)` but that's leaking an implementation details.
```javascript
const cancelId = this.runTask(reject, this.timeout);
// ... later
Ember.run.cancel(cancelId);
```
Ideally, the `cancelId` should be opaque to the caller. The caller shouldn't know that it's coming from `Ember.run`. We should add either:
```javascript
const cancelId = this.runTask(reject, this.timeout);
// ... later
this.cancelTask(cancelId);
```
or:
```javascript
const cancelTask = this.runTask(reject, this.timeout);
// ... later
cancelTask();
```

**Comment by rwjblue** [comment]
Sounds like a good idea.  I'd prefer the `this.cancelTask(someId)` option which avoids creating extra functions that are likely not going to be used...

**Comment by stefanpenner** [comment]
thoughts on `task.cancel()` ?

**Comment by mdebbar** [comment]
@stefanpenner what's `task`?

**Comment by stefanpenner** [comment]
maybe `let task = this.runTask(...)`

**Comment by scalvert** [comment]
As much as I like a clean API like `task.cancel()`, this doesn't seem to map to the inverse of `runTask` as much as `cancelTask` would. I wouldn't intuitively be able to discover this. 

What do you guys think?

**Comment by rwjblue** [comment]
I think its easier to start with `this.cancelTask`, and later iterate to allow the return value to be cancelable directly (e.g. `task.cancel()`).

**Comment by stefanpenner** [comment]
> What do you guys think?

I can accept that, since JS has the `clearTimeout` `setTimeout` pair.
