### ISSUE TITLE
task labels seem problematic

### ISSUE THREAD

**Issue by stefanpenner** [rwjblue/ember-lifeline#36]
https://github.com/rwjblue/ember-lifeline/blob/master/addon/mixins/run.js#L22-L24

These labels are global, this means that (for example) two components using the same labels will interfere with each other.

If these labels are used, they should most likely be scoped to the `this` in question, and not made global, or sad interleavings will occure.

I also believe these label methods should return explicit tokens to still explicitly cancel. Which would address the above described issues.

**Comment by scalvert** [comment]
I agree. I'll look into implementing this.

**Comment by stefanpenner** [comment]
re: tokens, we can mimic `setTimeout` `setInterval` and just have an incrementing ID.

```js
let last = 0;
export default function next() {
  return last++;
}
```

**Comment by scalvert** [comment]
👍
