### ISSUE TITLE
`addEventListener` does not work with jQuery objects

### ISSUE THREAD

**Issue by YoranBrondsema** [rwjblue/ember-lifeline#56]
[This change](https://github.com/rwjblue/ember-lifeline/pull/40/files#diff-73b723509639345f1a7008f7c9b9775aL284) removed the support for passing jQuery objects to `addEventListener` (see [here](https://github.com/rwjblue/ember-lifeline/blob/b2172407404d051f57bc24bd7be971dd66d7e11b/addon/mixins/dom.js#L155) for the current state of the file `addon/mixins/dom.js`). I'm not sure if that was intentional as [the documentation](https://github.com/rwjblue/ember-lifeline#addeventlistener) still says that they should work.

So either the documentation should be updated or the support for jQuery objects should be added back to the addon. I don't mind fixing either of these but I just wanted to make sure what the intention was before I started the work.

**Comment by rwjblue** [comment]
Thanks for reporting! We do not intend to do anything with jQuery so we should update the docs to match the behavior.

**Comment by rwjblue** [comment]
Fixed by #57
