### ISSUE TITLE
Add functional API (and use it from the mixin).

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-lifeline#6]
Examples:

```js
import { addEventListener, runTask } from 'ember-lifeline';

...

  didInsertElement() {
    this._super(...arguments);
    addEventListener(this, fn, { passive: true });
    runTask(this, 'fooMethod', 1000);
  }
```

Credit to @mitchlloyd and @cibernox for suggesting this.

**Comment by cibernox** [comment]
The main reason for this alternative API is to allow tree-shaking in the near future. I could also be more performant.

**Comment by knownasilya** [comment]
Also makes it clear where the functionality is coming from, especially from an on-boarding perspective.

**Comment by rwjblue** [comment]
Yes, completely agreed (on all accounts).

**Comment by scalvert** [comment]
Should we instead look for a path toward building some of this functionality inside Ember? This has been brought up a few times recently with @rwjblue and @stefanpenner.

**Comment by stefanpenner** [comment]
Ya, lets land it here. Make sure it feels good, then get and RFC out to ember.

I think this lifeline stuff is game changer when it comes to leaks / concurrency issues.

**Comment by scalvert** [comment]
👍  I'm creating a new branch to work on this.

**Comment by scalvert** [comment]
I've implemented the `*Tasks` portion of this issue in https://github.com/rwjblue/ember-lifeline/pull/66. I'm going to move on to create the functional equivalent for the DOM side.

**Comment by scalvert** [comment]
Implemented in:

- runTask to functional equivalent #63 
- *Task to functional equivalent #66 
- dom to functional equivalent #67

**Comment by scalvert** [comment]
All PRs have been merged. I'll release a beta and update the docs.
