### ISSUE TITLE
Unable to addEventListener to window in 3.0.x 

### ISSUE THREAD

**Issue by jrjohnson** [rwjblue/ember-lifeline#70]
This code no longer works after updating to v3.0.0

`this.addEventListener(window, 'mousemove', fn);` 

It triggers the assertion at https://github.com/rwjblue/ember-lifeline/blob/master/addon/dom-event-listeners.js#L147 as the `window` does not have a `nodeType` property.

**Comment by rwjblue** [comment]
Sorry about that! Thanks for working on the fix...
